# Change these first
owner: Midnigh7 # Your GitHub organization or username, where this repository lives
repo: StatusBoard # The name of this repository

sites:
  - name: Auvik
    url: https://mytech.us1.my.auvik.com/
     
  - name: Alloy
    url: https://cog.mytechpartners.net:9090/healthCheck
    __dangerous__insecure: true
    
  - name: ScreenConnect
    url: https://go.mytech.com

  - name: ScreenConnect Relay
    check: "tcp-ping"
    url: screlay.mytech.com
    port: 8080
    
  - name: N-Able
    url: https://Manage.mytech.com
    icon: https://www.n-able.com/wp-content/themes/nable.2021/img/favicon/favicon-16x16.png

  - name: ConnectWise Manage
    url: https://connect.mytech.com

  - name: Immy.Bot
    url: https://mytech.immy.bot

  - name: ITGlue
    url: https://mytech.itglue.com
    icon: https://www.itglue.com/favicon.ico

  - name: Rewst
    url: https://app.rewst.io
    icon: https://app.rewst.io/favicon.ico

  - name: NodeRed
    url: https://nodered.mytech.com/api?api=HealthCheck
    icon: https://nodered.mytech.com/favicon.ico
    __dangerous__body_down_if_text_missing: '"Status":"Healthy"'

  - name: Jamf
    url: https://mytech.jamfcloud.com/healthCheck.html
    icon: https://mytech.jamfcloud.com/favicon.ico


  - name: CloudFlare
    url: https://www.cloudflarestatus.com/api/v2/status.json
    headers:
        - "Content-Type: application/json"
    __dangerous__body_degraded: "indicator: minor" 
    __dangerous__body_down: "indicator: major" 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /StatusBoard
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: StatusBoard
  theme: night
 # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
 # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
